// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3o5TgErqfLpWby6LrMBpVCHVoEDy4M5U',
    appId: '1:1007023164029:web:11173197eff344c15dff14',
    messagingSenderId: '1007023164029',
    projectId: 'home-back-admin',
    authDomain: 'home-back-admin.firebaseapp.com',
    storageBucket: 'home-back-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsv-RJOh28PI5ViMDjtvJ23aC6jwLTnGE',
    appId: '1:1007023164029:android:719f8e4fd19adea15dff14',
    messagingSenderId: '1007023164029',
    projectId: 'home-back-admin',
    storageBucket: 'home-back-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXr731Wycp7KyUBoA4TllcaNFtctdY1-c',
    appId: '1:1007023164029:ios:480bba9f41bf23185dff14',
    messagingSenderId: '1007023164029',
    projectId: 'home-back-admin',
    storageBucket: 'home-back-admin.firebasestorage.app',
    iosBundleId: 'app.kambathagothi.homeBake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3o5TgErqfLpWby6LrMBpVCHVoEDy4M5U',
    appId: '1:1007023164029:web:b604954f516be2635dff14',
    messagingSenderId: '1007023164029',
    projectId: 'home-back-admin',
    authDomain: 'home-back-admin.firebaseapp.com',
    storageBucket: 'home-back-admin.firebasestorage.app',
  );
}
